Description: Container Cluster and Load Balencer

Resources:
  #--------------------------------------------------------------------
  #       Load balencing Resources
  #--------------------------------------------------------------------

  # the load balencer for the stack, the load balencer is responsible
  # for dealing with internet traffic/managing load on the website
  BiopathLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: Biopath-ECS-Services
      Scheme: internet-facing
      Subnets: [ !Ref 'PublicSubnetOne' , !Ref 'PublicSubnetTwo' ]
      SecurityGroups: [ !Ref BiopathLBSecurityGroup ]

  # the load balencer will define the format of incoming messages
  # to the rest of the project
  BiopathLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref BiopathLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref BiopathTargetGroup

  BiopathTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip 
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
  
  # this is for logging through AWS
  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 365  

  #--------------------------------------------------------------------
  #       Security Group Resources
  #--------------------------------------------------------------------
  BiopathBackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Biopath-backend security group
      SecurityGroupIngress:
      - CidrIp: '0.0.0.0/0'
        IpProtocol: tcp
        ToPort: 4567
        FromPort: 4567
      VpcId: !Ref 'VPC'

  BiopathFrontendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Biopath-frontend security group
      SecurityGroupIngress:
      - CidrIp: '0.0.0.0/0'
        IpProtocol: tcp
        ToPort: 80
        FromPort: 80
      VpcId: !Ref 'VPC'

  # the load balencer security group
  BiopathLBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: load balancer security group
      SecurityGroupIngress:
      - CidrIp: '0.0.0.0/0'
        IpProtocol: tcp
        ToPort: 80
        FromPort: 80
      VpcId: !Ref 'VPC'

Outputs:
  Cluster:
    Value: !Ref ECSCluster
    Export:
      Name: 'ECSCluster'

  Listener:
    Description: listener port 80
    Value: !Ref BiopathLoadBalancerListener
    Export:
      Name: 'Listener'

  FrontendContainerSecurityGroup:
    Description: frontend container security group
    Value: !Ref BiopathFrontendSecurityGroup
    Export:
      Name: 'FrontendContainerSecurityGroup'

  BiopathBackendSecurityGroup:
    Description: backend container security group
    Value: !Ref BiopathBackendSecurityGroup
    Export:
      Name: 'BackendContainerSecurityGroup'

  LoadBalancerDNS:
    Description: Domain name for the loadbalancer
    Value: !GetAtt BiopathLoadBalancer.DNSName
    Export:
      Name: 'DomainName'